### ISSUE TITLE
Bug: Hot reload dev server not working

### ISSUE THREAD

**Issue by tylerjlawson** [Elderjs/elderjs#211] opened 2021-09-11 18:39 UTC
I'd like to request that the dev server performs a hot reload on file save. It is noted in the docs that the developer needs to make changes, save, then reload. 

[source](https://elderguide.com/tech/elderjs/#:~:text=Navigate%20to%20http,see%20your%20changes.)

I'd be happy to attempt a PR for this if someone could point me in the right direction.

**Comment by nickreese** [comment] 2021-09-11 19:55
Look into this plugin: https://github.com/Elderjs/plugins/tree/master/packages/browser-reload

**Comment by tylerjlawson** [comment] 2021-09-11 22:25
@nickreese thanks for the quick response. I am seeing now that I already have that plugin from using the template project through `npx degit Elderjs/template my-project`. My browser is not reloading on new saves even with the template project right now. I have tried using node versions 14.17.3 & 16.3.0. I have also tried setting `reload` for the plugin settings as both true or false.

Would you mind checking the template or have any other ideas for something I could be doing wrong?

**Comment by nickreese** [comment] 2021-09-13 08:11
@tylerjlawson Pushed a fix. The issue is that in an earlier version of the Elder.js template I added the origin to example. This caused the plugin to be trying a websocket from example.

**Closed by nickreese** 2021-09-13 08:11 UTC
