### ISSUE TITLE
content.matchAll is not a function

### ISSUE THREAD

**Issue by Shuunen** [Elderjs/elderjs#9] opened 2020-08-14 11:27 UTC
Hi,

I just followed the getting started, degit & npm install without issues, then the npm start output this : 

```
xxx@yyy ~/Projects/elderjs-app
$ npm start

> elderjs-template@1.0.0 start C:\Users\xxx\Projects\elderjs-app
> npm run build:rollup && npm run dev:server


> elderjs-template@1.0.0 build:rollup C:\Users\xxx\Projects\elderjs-app
> rollup -c

rollup production === true. Because watch is undefined.

./node_modules/intersection-observer/intersection-observer.js → public\dist\static\intersection-observer.js...
created public\dist\static\intersection-observer.js in 772ms

./node_modules/systemjs/dist/s.min.js → public\dist\static\s.min.js...
created public\dist\static\s.min.js in 643ms

./src/routes/blog/Blog.svelte → ./___ELDER___/compiled/...
[!] (plugin svelte) TypeError: content.matchAll is not a function
src\routes\blog\Blog.svelte
TypeError: content.matchAll is not a function
    at markup (C:\Users\xxx\Projects\elderjs-app\node_modules\@elderjs\elderjs\build\partialHydration\partialHydration.js:6:33)
    at preprocess (C:\Users\xxx\Projects\elderjs-app\node_modules\svelte\src\compiler\preprocess\index.ts:86:27)

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elderjs-template@1.0.0 build:rollup: `rollup -c`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elderjs-template@1.0.0 build:rollup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-08-14T11_21_38_286Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! elderjs-template@1.0.0 start: `npm run build:rollup && npm run dev:server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the elderjs-template@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxx\AppData\Roaming\npm-cache\_logs\2020-08-14T11_21_38_333Z-debug.log
```

I'm using Node 10.16, Npm 6.9.0 & Windows 10 x64

**Comment by nickreese** [comment] 2020-08-14 11:45
What version of the plugin are you using? This bug was squashed a few releases back. Please try the latest version and let us know if you hit snags. 

(Working towards 100% code coverage as fast as we can.)

**Comment by Shuunen** [comment] 2020-08-14 11:52
I just did a fresh install 30min ago, so latest I guess no?

**Comment by halafi** [comment] 2020-08-14 12:18
@Shuunen probably caused by using node 10.16 (more specifically by https://stackoverflow.com/a/55691566), for the moment the guaranteed supported version is 12.

I would also expect that you get this error when running yarn / npm:

`The engine "node" is incompatible with this module. Expected version ">=12.16.1". Got "10.x.x"`

**Comment by nickreese** [comment] 2020-08-14 13:04
@Shuunen let us know if you get a chance to try node 12 lts and if you hit issues. Going to close this for now but feel free to reopen if upgrading doesn’t fix it.

**Closed by nickreese** 2020-08-14 13:04 UTC

**Comment by Shuunen** [comment] 2020-08-15 08:04
@halafi Yarn is doing this check but not Npm sadly

Everything is working fine with node 12, thanks 👍
