### ISSUE TITLE
Hydration not working when not using self-closing tag

### ISSUE THREAD

**Issue by arggh** [Elderjs/elderjs#38] opened 2020-09-20 21:31 UTC
Just starting out with Elderjs, but I ran into a weird issue.

This won't hydrate on the client:

```svelte
<Map hydrate-client={{}} ></Map>
```

...but this will:

```svelte
<Map hydrate-client={{}} />
```

I'm working with the v0.2.0 template.

**Comment by sw-yx** [comment] 2020-09-20 22:08
the issue is almost certainly with this regex - https://github.com/Elderjs/elderjs/blob/88060bcf97adb0909dbae39843f4e4820774f6c9/src/partialHydration/partialHydration.ts#L22 

if i think a little bit its understandable why children are not supported - hard to draw the line between what is hydrated and what isnt.

we should add a regex for the non-self-closing case and insert an error if found, should be quite cheap.

**Comment by nickreese** [comment] 2020-09-21 14:31
@arggh / @sw-yx  Good calls. :)

We will throw an error during rollup in v1 for `<Map hydrate-client={{}} ></Map>` style components. Adding this functionality now.

**Comment by sw-yx** [comment] 2020-09-21 15:01
ok nice. just note that people might try to insert children in those components too, so the regex may  have to accommodate that (i honestly dont know if this is possible) and optionally give a nice reason why we dont allow children in hydrated components

**Comment by nickreese** [comment] 2020-09-21 15:36
@sw-yx 

Here is the improved error text:

```
Elder.js only supports self-closing syntax on hydrated components. This means <Foo /> not <Foo></Foo> or <Foo>Something</Foo>. Offending component: ${offendingCode}. Slots and child components aren't supported during hydration as it would result in huge HTML payloads. If you need this functionality try wrapping the offending component in a parent component without slots or child components and hydrate that.
```

**Comment by sw-yx** [comment] 2020-09-21 16:33
love it

**Closed** 2020-09-22 18:26 UTC
